services:
  - type: web
    name: agentmanagement-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar -Dspring.profiles.active=prod target/AgentManagementBE-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080

databases:
  - name: agentmanagement-db
    databaseName: agentmanagement
    user: agentmanagement_user
    plan: free 